// Mismas claves/roles que helper/UsuariosHelper.js de la app RN.
export const CLAVES_PERMISOS = {
  inventario: 'inventario',
  turnos: 'turnos',
  reportes: 'reportes',
  ventas: 'ventas',
  dashboard: 'dashboard',
  clientes: 'clientes',
  estadoCuenta: 'estadoCuenta',
  compras: 'compras',
  reporteTurnos: 'reporteTurnos',
  reporteFechas: 'reporteFechas',
  arqueoCaja: 'arqueoCaja',
  estadisticas: 'estadisticas',
  notasVenta: 'notasVenta',
  consolidado: 'consolidado',
  registroVentas: 'registroVentas',
  kardex: 'kardex',
  comandosVoz: 'comandosVoz',
  configuracion: 'configuracion',
  informacion: 'informacion',
  usuarios: 'usuarios',
  crearProducto: 'crearProducto',
  editarProducto: 'editarProducto',
  eliminarProducto: 'eliminarProducto',
  ajustarStock: 'ajustarStock',
  verCostos: 'verCostos',
  anularVenta: 'anularVenta',
  cobrarCredito: 'cobrarCredito',
  imprimirTicket: 'imprimirTicket',
  abrirTurno: 'abrirTurno',
  cerrarTurno: 'cerrarTurno',
  rectificarCaja: 'rectificarCaja',
  corregirPago: 'corregirPago',
  egresos: 'egresos',
  auditoria: 'auditoria',
  verTodo: 'verTodo',
  sire: 'sire',
  ventasPorEmpleado: 'ventasPorEmpleado',
  rotacionInventario: 'rotacionInventario',
} as const

const ALL_TRUE = Object.fromEntries(Object.values(CLAVES_PERMISOS).map((k) => [k, true]))
const ALL_FALSE = Object.fromEntries(Object.values(CLAVES_PERMISOS).map((k) => [k, false]))

export const PERMISOS_POR_ROL: Record<string, Record<string, boolean>> = {
  ADMIN: { ...ALL_TRUE },
  GERENTE: { ...ALL_TRUE, usuarios: false, configuracion: false, eliminarProducto: false },
  CAJERO: {
    ...ALL_FALSE,
    ventas: true,
    turnos: true,
    dashboard: true,
    clientes: true,
    notasVenta: true,
    reportes: true,
    imprimirTicket: true,
    abrirTurno: true,
    cerrarTurno: true,
    cobrarCredito: true,
    crearProducto: true,
    editarProducto: true,
    ajustarStock: true,
    informacion: true,
    egresos: true,
  },
}

export const MODULOS = [
  { key: 'modulos', label: 'Módulos (Tabs)', permisos: ['inventario', 'turnos', 'reportes', 'ventas', 'dashboard'] },
  { key: 'drawer', label: 'Opciones del Menú', permisos: ['clientes', 'estadoCuenta', 'compras', 'reporteTurnos', 'reporteFechas', 'arqueoCaja', 'estadisticas', 'notasVenta', 'consolidado', 'registroVentas', 'kardex', 'comandosVoz', 'configuracion', 'informacion', 'usuarios', 'egresos', 'auditoria', 'sire', 'ventasPorEmpleado', 'rotacionInventario'] },
  { key: 'funciones', label: 'Funciones', permisos: ['crearProducto', 'editarProducto', 'eliminarProducto', 'ajustarStock', 'verCostos', 'anularVenta', 'cobrarCredito', 'imprimirTicket', 'abrirTurno', 'cerrarTurno', 'rectificarCaja', 'corregirPago'] },
  { key: 'accesos', label: 'Acceso Especial', permisos: ['verTodo'] },
]

export const LABELS_PERMISOS: Record<string, string> = {
  inventario: 'Inventario',
  turnos: 'Turnos',
  reportes: 'Reportes',
  ventas: 'Ventas',
  dashboard: 'Dashboard',
  clientes: 'Clientes',
  estadoCuenta: 'Estado de Cuenta',
  compras: 'Compras por Fecha',
  reporteTurnos: 'Reporte por Turnos',
  reporteFechas: 'Reporte por Fechas',
  arqueoCaja: 'Arqueo de Caja',
  estadisticas: 'Estadísticas',
  notasVenta: 'Notas de Venta',
  consolidado: 'Consolidado de Boletas',
  registroVentas: 'Registro Ventas SUNAT',
  kardex: 'Kardex por Producto',
  comandosVoz: 'Comandos de Voz',
  configuracion: 'Configuración',
  informacion: 'Información',
  usuarios: 'Gestión de Usuarios',
  crearProducto: 'Crear Producto',
  editarProducto: 'Editar Producto',
  eliminarProducto: 'Eliminar Producto',
  ajustarStock: 'Ajustar Stock',
  verCostos: 'Ver Costos',
  anularVenta: 'Anular Venta',
  cobrarCredito: 'Cobrar Crédito',
  imprimirTicket: 'Imprimir Ticket',
  abrirTurno: 'Abrir Turno',
  cerrarTurno: 'Cerrar Turno',
  rectificarCaja: 'Rectificar Caja',
  corregirPago: 'Corregir Pago',
  egresos: 'Egresos / Gastos',
  auditoria: 'Auditoría',
  verTodo: 'Ver todo (acceso especial)',
  sire: 'Registro SIRE',
  ventasPorEmpleado: 'Ventas por Empleado',
  rotacionInventario: 'Rotación de Inventario',
}

export const ROLES = ['ADMIN', 'GERENTE', 'CAJERO', 'PERSONALIZADO']

export function permisosPorRol(rol: string): Record<string, boolean> {
  return { ...(PERMISOS_POR_ROL[rol] || PERMISOS_POR_ROL.CAJERO) }
}
